#!/bin/bash

set -e

PKG_PATH="/home/sPIffer"
CERT_PATH="/home/sPIffer/src/certificate"

sudo chown -R root:root $PKG_PATH
sudo chmod -R 777 $PKG_PATH

# Recreate new certificate for webserver
cd $CERT_PATH
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt -config openssl.cnf

echo "# Launch BOOT script"
cd $PKG_PATH
sudo ./eth_iface_boot.sh
sudo ./config_net_analyzer.sh
echo "# sPIffer well installed."

exit 0
